server:
  port: 9090
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@121.37.145.2:1521:orcl
    username: SCOTT
    password: tzy634867556
  mvc:
    view:
      prefix: /pages/
      suffix: .html
